sudo: required
service:
  - docker

script:
  - docker docker build . --tag pgr301 --build-arg JAR_FILE=./build/libs/pgr301-0.0.1-SNAPSHOT.jar
  - docker run pgr301:latest
  - docker run -p 8080:8080 pgr301:latest
  - docker ps -a
