sudo: required
language: java
install: true
services:
- docker
script:
- chmod +x gradlew
- "./gradlew build"
- ./Dspring.profiles.active=prod
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build . --tag pgr301 --build-arg JAR_FILE=./build/libs/pgr301-0.0.1-SNAPSHOT.jar
- docker ps -a
- docker tag pgr301 $DOCKER_USERNAME/devops
- docker push $DOCKER_USERNAME/devops
deploy:
provider: heroku
app: pgr301-exam-app-dev
api_key:
  secure: HaeDu4E8MeLzDT1NrE1M2Q+Bm2wlJ1Ckl95px89wwfG7+O3Czsv+xjLJYb5t3A4hA5D3oAumLWHwel29b81B8tmFRuN+sSQui4tI/7sKE5p4gv7qXRpYIN6RQpgxOl3tbBthw3z0GQI2JVNzs9a/Tsc4HK1KU4ZIE6YvTq+p8B99sT2wZ8gAoKtssfs9ISR9wKsbxHOm6NqeSeUnDQOzCAyz6DREv0HD+L4MBBjBJM1J8YJ0rFi4fgnJCoedwMgu8tQ2ntm8Dg4XZquS7WzWi6mkVvN0SfBNTspqYyJwzK0jtXLzHnYG/cVzUJgVuKMbBzyNbACZVQGvhCpz5HFM4URbWHf27LtBFJZMYbiA6149obkge14ENjFMrbbAZeW3hH0nCD2gnzXmI9D3wJTBOC9SpNlZOUDETgWFa/B7MgnoeRf8uM83eZi9SnzbvmP71mHQvdilE1LBkIN3vo6k+pa0Ih5GKx5OJc6L59Vlpo2gp3CAb7dN2ZwQcuUSRA6BcN6+bleMgRwwirch0M8dFzjXmqOaIDBqtO+LA/QGMDcgIFuwftrO9LYkGAj4p+LqFHU6eXafCYb1QkoQtRB0NbRFtMwLFdCvj02OHtdYQ9pfFAXIdczdwwyD+XgpxfRC9D4SEdFsv5AvCQ1K/BzsmK4ginaXllM6Yh7IlCXdIW4=
env:
  global:
  - secure: GootjXQ2bcbGWWAdz8vB01J2mkejwO2YArfZ8SOlCaYvSA2R3HBTH9U+ClG/H/Nd+cR/gYdFgU3ELqBEf10IOFATGYEyOJmCjCEgpHwuQmtA1a3KiBzhj0PW1kWuH61B1BkVsHFcApVXwGjbqYOG/+pIewbmgg1pAYQOos/PhRtYLzFadl+XEDI6VC5BOsy5Ga0AXcEwlkgXt9RcXzkH9Rd6qeupS4mHDUOLJMS1vq7dO4NeCg3u1VDhmyGbheyMTw4hO1WdK6JENCn00A9tQ55TUB8fTwY+YbetNMQ+ejzwY6TMvHBVBiVcSAYUfblRSxn8cAkquqsRFwewt2PcgXOsTpT13CwCY4ybFMWginXUCBkv1n5C0uArxzo03mJ9cDQFnHY91dhtBiBznrc3IkLYnv+a1f1wYOSdJVQjhZbdY0oZRUsFUjab+A7pvClWnhwWaXtE8Q9J6QLsIjlCUUhCAiiKslaqrzFi2btuCbfLSiP1/4T7sewpaJHJNC1DvF83dwxlbebF0pgKlfAHfIZp4OC6wFzmXKO8kRPmkhCecw2cMSYj4X0A2UdOMpScpEiepQHMEryqjl+hxPASsBlnMFeY9N9s50NonwCgTzfQ2xC9elaKJ63GBRibZ/0CBbFn7poMVDD+aX8eH2ScffxPeC3CewczzLdCPMQKqZc=
  - secure: Gpv+Xrl7IvvFDUs94TgYSxbq4enBmlMT3tt6BfXrLyqu6fLA1szDIHbR7AttChkpC+sXtBz/C28l50ARWFq/f+D4fAolKcDjBE6Vowpg+PHpoI0nJPZBgcg8mqTlncurt45VTOG2i6ZIfyuRH9W0+S8ZYjPaZtb7DX2INcNCqHRcO8TsyBLx3PM7QYevR+zd1EOp6J4BtYn+gjolQClZ6sNG9A3wg7ke+S0CQkbRMs1fLirw3iUB5FeIdN5h7EIfGsx6+a7oUZh413lzepcWUIFpJ7xrgXGvM/VX0czL5fstiFgOti24rtAzfmnNUWmlT6cO75ciTfcYTeVDi8gS899KTE/UX1P3G1ovPWosbVw4YigVMzF936rU2deL0icqYBL8gQTPyHy8DY4vc7jE5cc/OII2O/HPyIvHNeNzUeBQ5hxVCyEQN6Q4MwsjDOfahaepx6MhguB6b7jKj6lQaJaNA7WsShkP0lKzjbQ8aDgeZdGZh5bPHxD0WSwi4qnWGvfnXgWFVFrumypFyR4c3xMyGrBUuu+8as94Vq9baqdjdqX8R239FpIs86EYmR6DQ9PIbyoj9EDkZNXd9SUcIcI9sN6X7U5BAYsYsXwO5q3sE+USjNabLdPT2W/AH9ZMTkUnhzqyO68+ZFzPpJY5tVC2UztNJSvZSTZdnLdlXdw=
