sudo: required
language: java
install: true

services:
  - docker

after_install:
  - docker build . --tag pgr301 --build-arg JAR_FILE=./build/libs/

script:
  - chmod +x gradlew
  - ./gradlew build
  - docker build . --tag pgr301 --build-arg JAR_FILE=./build/libs/
  - docker run -p 8080:8080 pgr301:latest
  - docker ps -a




